### ISSUE TITLE
Problem with running example app

### ISSUE THREAD

**Issue by CH1M4C** [CalebFenton/simplify#87] opened 2017-08-30 04:21 UTC
Hello.
I am really sorry but I can not solve this problem for a week please help me....
I clone repository with "git clone --recursive https://github.com/CalebFenton/simplify.git" this command and "./gradlew fatjar" use this commad with java 8. build successful but not works for "obfucated-example" :(

I'm not sure, but the problem is that "AndroidFrameworkSmali" doesn't have "com/sun/crypto/provider/DESKey" this smali file.

11:56:03.346 INFO  Main         - Options:
Input file: simplify/obfuscated-example
Output file: obfuscated-example_simple.dex
Include filter: org/cf
Exclude filter: null
Max execution time: 300
Max address visits: 10000
Max call depth: 50
Max method visits: 1000000
Max optimization passes: 100
Output API level: 15
Include support library: false
[1 / 22] Processing top level class Lorg/cf/obfuscated/Reflection;
(1 / 8) Executing top level method: Lorg/cf/obfuscated/Reflection;->secretMethod2()V
11:56:12.330 INFO  MethodExecutor - Executing Lorg/cf/obfuscated/Reflection;-><clinit>()V, depth=0
11:56:12.425 INFO  MethodExecutor - Executing Lorg/cf/obfuscated/Reflection;->secretMethod2()V, depth=0
Simplifying: Lorg/cf/obfuscated/Reflection;->secretMethod2()V
Optimizations:
	constantized ifs = 0
	constantized ops = 0
	dead assignments removed = 0
	dead ops removed = 0
	dead results removed = 0
	nops removed = 0
	peephole optmizations = 0
	unreflected fields = 0
	unreflected methods = 0
	useless gotos removed = 0
(2 / 8) Executing top level method: Lorg/cf/obfuscated/Reflection;->reflectSecretMethod2()V
11:56:12.506 INFO  MethodExecutor - Executing Lorg/cf/obfuscated/Reflection;-><clinit>()V, depth=0
11:56:12.667 INFO  MethodExecutor - Executing Lorg/cf/obfuscated/Reflection;->reflectSecretMethod2()V, depth=0
11:56:12.730 INFO  MethodExecutor - Executing Lorg/cf/obfuscated/StringHolder;-><clinit>()V, depth=0
11:56:13.063 INFO  MethodExecutor - Executing Lorg/cf/obfuscated/StringHolder;->cacheStrings()Ljava/util/Map;, depth=1
11:56:13.319 INFO  MethodExecutor - Executing Lorg/cf/obfuscated/XORCrypt;->decode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;, depth=2
11:56:13.407 INFO  MethodExecutor - Executing Lorg/cf/obfuscated/XORCrypt;->decode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;, depth=2
11:56:13.499 INFO  MethodExecutor - Executing Lorg/cf/obfuscated/DESCrypt;-><clinit>()V, depth=0
11:56:13.776 INFO  MethodExecutor - Executing Lorg/cf/obfuscated/DESCrypt;->decrypt([BLjava/lang/String;)Ljava/lang/String;, depth=2
11:56:13.817 WARN  NodeExecutor - ExecutionNode{signature=Lorg/cf/obfuscated/DESCrypt;->decrypt([BLjava/lang/String;)Ljava/lang/String;, op=invoke-virtual {r6, r7, r4}, Ljavax/crypto/Cipher;->init(ILjava/security/Key;)V, @=21} threw a real exception but was caught by an exception handler. This may be a bug in smalivm or in the input code. Exception: java.lang.RuntimeException: Can't find Smali file for Lcom/sun/crypto/provider/DESKey;
11:56:13.821 WARN  NodeExecutor - ExecutionNode{signature=Lorg/cf/obfuscated/StringHolder;->cacheStrings()Ljava/util/Map;, op=invoke-static {r7, r13}, Lorg/cf/obfuscated/DESCrypt;->decrypt([BLjava/lang/String;)Ljava/lang/String;, @=108} threw a real exception but was caught by an exception handler. This may be a bug in smalivm or in the input code. Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/DESCrypt;->decrypt([BLjava/lang/String;)Ljava/lang/String;, op=invoke-virtual {r2}, Ljava/lang/Throwable;->printStackTrace()V, @=37} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
11:56:13.822 WARN  NodeExecutor - ExecutionNode{signature=Lorg/cf/obfuscated/Reflection;->reflectSecretMethod2()V, op=invoke-static {r3}, Lorg/cf/obfuscated/StringHolder;->get(I)Ljava/lang/String;, @=2} threw a real exception but was caught by an exception handler. This may be a bug in smalivm or in the input code. Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/StringHolder;-><clinit>()V, op=invoke-static {}, Lorg/cf/obfuscated/StringHolder;->cacheStrings()Ljava/util/Map;, @=112} and was not handled. This could be a bug in smalivm.
Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/StringHolder;->cacheStrings()Ljava/util/Map;, op=invoke-virtual {r5}, Ljava/lang/Throwable;->printStackTrace()V, @=129} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
Exception in thread "main" java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/Reflection;->reflectSecretMethod2()V, op=invoke-virtual {r0}, Ljava/lang/Throwable;->printStackTrace()V, @=32} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:88)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:187)
	at org.cf.simplify.Launcher.run(Launcher.java:151)
	at org.cf.simplify.Main.main(Main.java:14)

**Comment by CalebFenton** [comment] 2017-08-30 15:19
Thanks for the error report. I confirmed it is a problem.

It looks like the app still compiles using target API of 25, so either it was removed in a later API or it somehow didn't make it to the framework repo. I'll look into this later today, hopefully. Should be an easy fix. Just need to pull the framework off an emulator and try and find the missing classes (and also figure out how I missed them).

**Comment by CalebFenton** [comment] 2017-08-31 02:32
I understand this problem better now. Some crypto classes are marked safe for reflection, and when you use reflection to get a Cipher instance of DES, you get the `com.sun.crypto.provider.DESKey` from the JVM, rather than the Android framework. On Android you get like a DESKeySpec or something. I think the fix will either take the form of either:
1. carefully white listing classes, possibly emulating a few
2. emulating key crypto classes
3. using reflection and using the JVM-specific classes, but making the class manager less strict about requiring classes have a backing smali file. this may mean just adding stubs.

**Comment by thehesiod** [comment] 2017-09-07 07:02
how do we run it with API of 25?

**Comment by CalebFenton** [comment] 2017-09-07 17:40
Depends on which of the 10 ways you interpret that question. Simplify already uses API 25.

**Comment by thehesiod** [comment] 2017-09-07 18:43
oh sorry, misread your statement.  Was trying to figure out if there's any way to run it

**Comment by enovella** [comment] 2017-10-16 09:53
Hi,

getting similar error:

```
$ java -jar simplify/build/libs/simplify.jar -it 'org/cf' simplify/obfuscated-example
[1 / 22] Processing top level class Lorg/cf/obfuscated/Reflection;
(1 / 8) Executing top level method: Lorg/cf/obfuscated/Reflection;->secretMethod2()V
Simplifying: Lorg/cf/obfuscated/Reflection;->secretMethod2()V
Optimizations:
	constantized ifs = 0
	constantized ops = 0
	dead assignments removed = 0
	dead ops removed = 0
	dead results removed = 0
	nops removed = 0
	peephole optmizations = 0
	unreflected fields = 0
	unreflected methods = 0
	useless gotos removed = 0
(2 / 8) Executing top level method: Lorg/cf/obfuscated/Reflection;->reflectSecretMethod2()V
11:50:29.042 WARN  NodeExecutor - ExecutionNode{signature=Lorg/cf/obfuscated/DESCrypt;->decrypt([BLjava/lang/String;)Ljava/lang/String;, op=invoke-virtual {r6, r7, r4}, Ljavax/crypto/Cipher;->init(ILjava/security/Key;)V, @=21} threw a real exception but was caught by an exception handler. This may be a bug in smalivm or in the input code. Exception: java.lang.RuntimeException: Can't find Smali file for Lcom/sun/crypto/provider/DESKey;
11:50:29.066 WARN  NodeExecutor - ExecutionNode{signature=Lorg/cf/obfuscated/StringHolder;->cacheStrings()Ljava/util/Map;, op=invoke-static {r7, r13}, Lorg/cf/obfuscated/DESCrypt;->decrypt([BLjava/lang/String;)Ljava/lang/String;, @=108} threw a real exception but was caught by an exception handler. This may be a bug in smalivm or in the input code. Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/DESCrypt;->decrypt([BLjava/lang/String;)Ljava/lang/String;, op=invoke-virtual {r2}, Ljava/lang/Throwable;->printStackTrace()V, @=37} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
11:50:29.067 WARN  NodeExecutor - ExecutionNode{signature=Lorg/cf/obfuscated/Reflection;->reflectSecretMethod2()V, op=invoke-static {r3}, Lorg/cf/obfuscated/StringHolder;->get(I)Ljava/lang/String;, @=2} threw a real exception but was caught by an exception handler. This may be a bug in smalivm or in the input code. Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/StringHolder;-><clinit>()V, op=invoke-static {}, Lorg/cf/obfuscated/StringHolder;->cacheStrings()Ljava/util/Map;, @=112} and was not handled. This could be a bug in smalivm.
Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/StringHolder;->cacheStrings()Ljava/util/Map;, op=invoke-virtual {r5}, Ljava/lang/Throwable;->printStackTrace()V, @=129} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
Exception in thread "main" java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/Reflection;->reflectSecretMethod2()V, op=invoke-virtual {r0}, Ljava/lang/Throwable;->printStackTrace()V, @=32} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:88)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:185)
	at org.cf.simplify.Launcher.run(Launcher.java:149)
	at org.cf.simplify.Main.main(Main.java:14)
```

**Comment by CalebFenton** [comment] 2017-10-16 17:25
@enovella Looks like a class was removed from the framework which the sample app used. I think the solution is to just rewrite the sample app to use a different type of encryption. Shouldn't take long to fix but I've been hella busy, sorry.

More info here: https://github.com/CalebFenton/simplify/issues/89

**Comment by CalebFenton** [comment] 2018-10-04 14:48
This should be fixed since around https://github.com/CalebFenton/simplify/commit/7c56553db164ae7a74662f90ed3e3abd7aa5826d

**Closed by CalebFenton** 2018-10-04 14:48 UTC
