### ISSUE TITLE
Potentially unintentional package name change during simplification

### ISSUE THREAD

**Issue by droidresearch** [CalebFenton/simplify#153] opened 2020-12-04 19:23 UTC
**Provide specific APK, DEX, or file hash**
https://github.com/CalebFenton/simplify/blob/master/simplify/obfuscated-app.apk

**Describe the bug**
The awesome simplify project does simplify the code given in the example obfuscated app (WhiteNoise.java). However, there is a change to the package name as part of the simplification. This might be an unintentional as per the inventor of the project, the smalivm does not have the logic to rename the package name. 

**To Reproduce**
java -jar simplify/build/libs/simplify.jar -it 'org/cf/obfuscated' -et 'MainActivity' simplify/obfuscated-app.apk

**Attempted work-arounds**
I have read the README and I am trying to read the code to understand whether I can contribute any root cause.

**Screenshots**
![image](https://user-images.githubusercontent.com/14039691/101205814-31977000-3694-11eb-8266-1b4d14ce83bd.png)

**Comment by CalebFenton** [comment] 2020-12-05 05:13
Thanks for the issue @droidresearch. What you use for decompilation?

**Comment by droidresearch** [comment] 2020-12-05 05:15
Hi @CalebFenton, I used jadx-1.2 version (https://github.com/skylot/jadx/releases/tag/v1.2.0)

**Comment by CalebFenton** [comment] 2020-12-08 23:07
I'm unable to reproduce the issue on a Mac. I don't think the issue is with simplify because in your example the unobfuscated app says the package was renamed from org.cf.obfuscated.WhiteNoise. This reads like Jadx renamed the package for some reason, and then probably semi-randomly renamed it again when you decompiled the simplified version.
<img width="897" alt="Screen Shot 2020-12-08 at 3 04 27 PM" src="https://user-images.githubusercontent.com/1356658/101552069-04ceab80-3967-11eb-98d8-37e08b8a8fd7.png">

How'd you run jadx?

Closing, but feel free to continue commenting here.

**Closed by CalebFenton** 2020-12-08 23:07 UTC

**Comment by CalebFenton** [comment] 2020-12-08 23:13
Ah, I think I see. This command produces the output you're seeing:

```
./jadx --deobf --deobf-min 3  ~/repos/simplify/obfuscated-app_simple.apk
```

And the relevant bits from the readme:

```
  --deobf                             - activate deobfuscation
  --deobf-min                         - min length of name, renamed if shorter, default: 3
```

jadx considers `cf` in the package name to be too short and is padding it as part of its deobfuscation logic.

**Comment by droidresearch** [comment] 2020-12-09 02:04
Thanks, @Caleb.. This is interesting. I will check the decompiler’s default options and take a look at its deobf logic as well.
