### ISSUE TITLE
Many exceptions raised during deobfuscation

### ISSUE THREAD

**Issue by marcellmajor** [CalebFenton/simplify#40] opened 2016-01-26 10:38 UTC
The APK has DexGuard, but apparently not obfuscated, the messages:

Executing: Ldexguard/util/AntiHooking;->a(Ljava/lang/String;Ljava/lang/Runtime;[Ljava/lang/Class;[Ljava/lang/Object;)Ljava/lang/Object;
11:31:16.984 INFO  MethodExecutor - Executing Ldexguard/util/AntiHooking;-><clinit>()V, depth=0
11:31:17.031 INFO  MethodExecutor - Executing Ldexguard/util/AntiHooking;->a()Ljava/lang/Class;, depth=1
11:31:17.068 INFO  MethodExecutor - Executing Ldexguard/util/AntiHooking;->a(SIB)Ljava/lang/String;, depth=2
11:31:17.254 INFO  MethodExecutor - Executing Ldexguard/util/AntiHooking;->a(Ljava/lang/String;Ljava/lang/Runtime;[Ljava/lang/Class;[Ljava/lang/Object;)Ljava/lang/Object;, depth=0
11:31:17.274 WARN  NewArrayOpFactory - Ljava/lang/Class; is framework but not safe; will treat as if it doesn't exist.
11:31:17.275 INFO  MethodExecutor - Executing Ldexguard/util/AntiHooking;->a(Ljava/lang/reflect/Method;Ljava/lang/Runtime;[Ljava/lang/Object;)Ljava/lang/Object;, depth=1
11:31:17.277 INFO  MethodExecutor - Executing Ldexguard/util/AntiHooking;->a(SIB)Ljava/lang/String;, depth=2
11:31:17.323 INFO  MethodExecutor - Executing Ldexguard/util/AntiHooking;->a(SIB)Ljava/lang/String;, depth=2
11:31:17.395 WARN  NodeExecutor - aput-object r3, r2, r4 generated a real exception:
java.lang.IllegalArgumentException: array element type mismatch
	at java.lang.reflect.Array.set(Native Method) ~[na:1.8.0_66]
	at org.cf.smalivm.opcode.APutOp.execute(APutOp.java:127) ~[simplify-0.9.1.jar:na]
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:56) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:97) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:100) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:295) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:152) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:58) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:97) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:100) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77) [simplify-0.9.1.jar:na]
	at org.cf.simplify.Launcher.executeClass(Launcher.java:101) [simplify-0.9.1.jar:na]
	at org.cf.simplify.Launcher.run(Launcher.java:69) [simplify-0.9.1.jar:na]
	at org.cf.simplify.Main.main(Main.java:14) [simplify-0.9.1.jar:na]
11:31:17.398 WARN  NodeExecutor - invoke-static {r2, r3, r5}, Ldexguard/util/AntiHooking;->a(Ljava/lang/reflect/Method;Ljava/lang/Runtime;[Ljava/lang/Object;)Ljava/lang/Object; generated a real exception:
java.lang.NullPointerException: null
	at org.cf.smalivm.context.ExecutionGraph.getTemplateNode(ExecutionGraph.java:398) ~[simplify-0.9.1.jar:na]
	at org.cf.smalivm.NodeExecutor.spawnChild(NodeExecutor.java:51) ~[simplify-0.9.1.jar:na]
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:39) ~[simplify-0.9.1.jar:na]
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:97) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:100) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:295) ~[simplify-0.9.1.jar:na]
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:152) ~[simplify-0.9.1.jar:na]
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:58) ~[simplify-0.9.1.jar:na]
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31) ~[simplify-0.9.1.jar:na]
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:97) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:100) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82) [simplify-0.9.1.jar:na]
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77) [simplify-0.9.1.jar:na]
	at org.cf.simplify.Launcher.executeClass(Launcher.java:101) [simplify-0.9.1.jar:na]
	at org.cf.simplify.Launcher.run(Launcher.java:69) [simplify-0.9.1.jar:na]
	at org.cf.simplify.Main.main(Main.java:14) [simplify-0.9.1.jar:na]
Exception in thread "main" java.lang.NullPointerException
	at org.cf.smalivm.context.ExecutionGraph.getTemplateNode(ExecutionGraph.java:398)
	at org.cf.smalivm.NodeExecutor.spawnChild(NodeExecutor.java:51)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:39)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:97)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:100)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:101)
	at org.cf.simplify.Launcher.run(Launcher.java:69)
	at org.cf.simplify.Main.main(Main.java:14)

**Comment by CalebFenton** [comment] 2016-01-27 03:22
Thank you for taking the time to post this error. It's related to this one: https://github.com/CalebFenton/simplify/issues/25

The problem is that this is trying to create an array of `java.lang.Class`. The problem with this is that smalivm handles classes in two different ways: for non-local types (those defined by the JVM like `java.lang.String`) are created as actual `java.lang.Class` instances, but local types (those defined by smali files you give as input) are created as `LocalClass` instances. This means they won't go into an array of `[Ljava/lang/Class;`.

I've been working on a solution to dynamically create JVM classes for arbitrary smali files (dexlib class definitions) but I'm running a lot of tiny problems such as missing dependencies and not being able to create classes in the `java.lang` package. Hopefully I can sort those problems out and this should work better.

Could you post the MD5 or SHA1 of the APK? It would be nice to test it as soon as I can make the aforementioned changes.

**Comment by CalebFenton** [comment] 2016-02-15 18:08
Without the sha1, this is impossible to reproduce and fix.

**Comment by CalebFenton** [comment] 2016-02-17 03:00
The real exception here is `java.lang.IllegalArgumentException: array element type mismatch` and it appears the array type is `[Ljava/lang/Class;`. These issues should have been fixed in Milestone 1.

**Closed by CalebFenton** 2016-02-17 03:00 UTC

**Comment by marcellmajor** [comment] 2016-04-20 07:22
Hi Caleb,

Sorry for the late answer. I cannot give you APK as it is a commercial
product and against the company's contract.
However it has the commercial version of dexguard qapplied, I think that
causes these issues...

Regards,
Marcell
