### ISSUE TITLE
Gradle build fail

### ISSUE THREAD

**Issue by Lemniscate317** [CalebFenton/simplify#130] opened 2019-09-08 07:45 UTC
I run this command
```
gradlew fatjar --stacktrace --info

```

And this the error log
```
* What went wrong:
Failed to capture snapshot of input files for task 'compileJava' property 'classpath' during up-to-date check.
> Error snapshotting jar [smalivm-1.2.1.jar]

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.UncheckedIOException: Failed to capture snapshot of input files for task 'compileJava' property 'classpath' during up-to-date check.
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.buildSnapshots(AbstractNamedFileSnapshotTaskStateChanges.java:93)
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.<init>(AbstractNamedFileSnapshotTaskStateChanges.java:58)
        at org.gradle.api.internal.changedetection.rules.InputFilesTaskStateChanges.<init>(InputFilesTaskStateChanges.java:29)
        at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:60)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:178)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:88)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.UncheckedIOException: Error snapshotting jar [smalivm-1.2.1.jar]
        at org.gradle.api.internal.changedetection.state.AbstractClasspathSnapshotBuilder$JarHasher.hashJarContents(AbstractClasspathSnapshotBuilder.java:111)
        at org.gradle.api.internal.changedetection.state.AbstractClasspathSnapshotBuilder$JarHasher.hash(AbstractClasspathSnapshotBuilder.java:92)
        at org.gradle.api.internal.changedetection.state.ResourceSnapshotterCacheService.hashFile(ResourceSnapshotterCacheService.java:45)
        at org.gradle.api.internal.changedetection.state.AbstractClasspathSnapshotBuilder.visitJar(AbstractClasspathSnapshotBuilder.java:82)
        at org.gradle.api.internal.changedetection.state.AbstractClasspathSnapshotBuilder.visitFileSnapshot(AbstractClasspathSnapshotBuilder.java:75)
        at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitCollection(AbstractFileCollectionSnapshotter.java:75)
        at org.gradle.api.internal.file.AbstractFileCollection.visitRootElements(AbstractFileCollection.java:234)
        at org.gradle.api.internal.file.CompositeFileCollection.visitRootElements(CompositeFileCollection.java:185)
        at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:51)
        at org.gradle.api.internal.changedetection.state.DefaultCompileClasspathSnapshotter.snapshot(DefaultCompileClasspathSnapshotter.java:36)
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.buildSnapshots(AbstractNamedFileSnapshotTaskStateChanges.java:91)
        ... 31 more
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
        at org.gradle.api.internal.changedetection.state.ZipTree.visit(ZipTree.java:44)
        at org.gradle.api.internal.changedetection.state.AbstractClasspathSnapshotBuilder$JarHasher.hashJarContents(AbstractClasspathSnapshotBuilder.java:104)
        ... 41 more

==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Failed to capture snapshot of input files for task 'compileJava' property 'classpath' during up-to-date check.
> Error snapshotting jar [smalivm-1.2.1.jar]

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.UncheckedIOException: Failed to capture snapshot of input files for task 'compileJava' property 'classpath' during up-to-date check.
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.buildSnapshots(AbstractNamedFileSnapshotTaskStateChanges.java:93)
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.<init>(AbstractNamedFileSnapshotTaskStateChanges.java:58)
        at org.gradle.api.internal.changedetection.rules.InputFilesTaskStateChanges.<init>(InputFilesTaskStateChanges.java:29)
        at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:60)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:178)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:88)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.api.UncheckedIOException: Error snapshotting jar [smalivm-1.2.1.jar]
        at org.gradle.api.internal.changedetection.state.AbstractClasspathSnapshotBuilder$JarHasher.hashJarContents(AbstractClasspathSnapshotBuilder.java:111)
        at org.gradle.api.internal.changedetection.state.AbstractClasspathSnapshotBuilder$JarHasher.hash(AbstractClasspathSnapshotBuilder.java:92)
        at org.gradle.api.internal.changedetection.state.ResourceSnapshotterCacheService.hashFile(ResourceSnapshotterCacheService.java:45)
        at org.gradle.api.internal.changedetection.state.AbstractClasspathSnapshotBuilder.visitJar(AbstractClasspathSnapshotBuilder.java:82)
        at org.gradle.api.internal.changedetection.state.AbstractClasspathSnapshotBuilder.visitFileSnapshot(AbstractClasspathSnapshotBuilder.java:75)
        at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitCollection(AbstractFileCollectionSnapshotter.java:75)
        at org.gradle.api.internal.file.AbstractFileCollection.visitRootElements(AbstractFileCollection.java:234)
        at org.gradle.api.internal.file.CompositeFileCollection.visitRootElements(CompositeFileCollection.java:185)
        at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:51)
        at org.gradle.api.internal.changedetection.state.DefaultCompileClasspathSnapshotter.snapshot(DefaultCompileClasspathSnapshotter.java:36)
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.buildSnapshots(AbstractNamedFileSnapshotTaskStateChanges.java:91)
        ... 34 more
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
        at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140)
        at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118)
        at org.gradle.api.internal.changedetection.state.ZipTree.visit(ZipTree.java:44)
        at org.gradle.api.internal.changedetection.state.AbstractClasspathSnapshotBuilder$JarHasher.hashJarContents(AbstractClasspathSnapshotBuilder.java:104)
        ... 44 more

==============================================================================

BUILD FAILED in 39s
7 actionable tasks: 4 executed, 3 up-to-date
Stopped 0 worker daemon(s).

```

I aslo google the log, but get nothing ,so i have no idea that why happen this?
Hope get the reply,thanks

**Comment by CalebFenton** [comment] 2019-09-08 14:31
I've never seen this before. Did you clone recursively? What gradle version
are you using? Do other tasks like `gradle clean work`?

**Comment by Lemniscate317** [comment] 2019-09-08 14:51
I just run 
```
gradlew clean
gradlew fatjar
```
And it also goes wrong.

I run this command to download
```
git clone --recursive https://github.com/CalebFenton/simplify.git
```
So it will download the submodule.

I don't have the gradle env,so it auto downlaod the gradle 4.0 when i run gradlew fatjar. And the version is same with this project.

Have any suggest?

**Comment by CalebFenton** [comment] 2019-09-08 15:01
The underlying error seems to be `Unexpected end of ZLIB input stream` but the actual file that's possibly corrupt isn't mentioned. Could you try deleting and cloning again? Maybe the framework jar wasn't downloaded completely.

Does `assemble` work? You're running `./gradlew` right and not actually `gradlew`?

Let your persistence be vitalized by the assumption that this problem is not inherent with the project but rather your environment.

**Comment by Lemniscate317** [comment] 2019-09-08 15:46
I don't understand  what is ```assemble``` . The error is occur in wondows 8.1  . Even if i redownload again , the error is still occur . And i run this in mac , it is good and create the jar success. The process  is same as the windows. In windows , I run 'gradlew.bat' instead of './gradlew'. But it will occur the error. My english is not good , sorry for that . And i think it is hard to solve this , but now i can cp the jar from mac to try this project . Thanks your project

**Comment by CalebFenton** [comment] 2019-09-11 18:00
Closing since this is a problem with your environment.

`assemble` is one of the built in tasks for gradle. It basically just compiles the java and doesn't do much else. It's a less complicated task than fatjar so it's sometimes good for troubleshooting.

Please try googling some of your errors as they seem to be caused by gradle and your environment.

**Closed by CalebFenton** 2019-09-11 18:00 UTC
