### ISSUE TITLE
Simplify don't see reflection and encryption string.

### ISSUE THREAD

**Issue by maxben14** [CalebFenton/simplify#70] opened 2017-04-10 22:06 UTC
I try delete reflection and ecryption string in my apk which packed with dexprotector.
In ProtectedApp.smali there are encrypt string and reflection class methods.
For examle method decrypt string and reflection class:
    const-string v31, "\u2ea0\u9661\u60ad\u7c88\u4944\ub51d\ub144\u8c6e\uf953\u688b\ub7e3\uddb6\u9f47\ucfdc\uedf7\u3195"
    invoke-static/range {v31 .. v31}, Lru/novacard/siticard/ProtectedApp;->a(Ljava/lang/String;)Ljava/lang/String;
    move-result-object v31
    invoke-static/range {v31 .. v31}, Ljava/lang/Class;->forName(Ljava/lang/String;)Ljava/lang/Class;

My log:
[simpl.txt](https://github.com/CalebFenton/simplify/files/911589/simpl.txt)

I try call simplify with this command.
java -jar simplify/build/libs/simplify.jar -it 'ru/novacard/siticard/ProtectedApp' -et 'android/support' -o classes.dex SitiCard/smali
I get new classed.dex but reflection and ecrypt string again there are in new dex file.
Why so and how fixed ?
If you need my apk, i can upload apk you for research.

**Comment by CalebFenton** [comment] 2017-04-12 18:13
Could you link to the apk? If you can't share, could you at least give the file hash and I'll see if I can find it?

What version of simplify are you using? Your log is showing a lot of errors that very likely could be bugs.

**Comment by maxben14** [comment] 2017-04-12 18:15
Please say your e-mail, i will send apk on e-mail.

**Comment by CalebFenton** [comment] 2017-04-12 18:17
calebjfenton@gmail.com

**Comment by maxben14** [comment] 2017-04-12 18:25
I send apk.

**Comment by maxben14** [comment] 2017-04-12 18:27
My apk http://rgho.st/68gldNwQV can download this link.I build simplify on last day, i think last version. 12.04.2017, 21:13, "Caleb Fenton" <notifications@github.com>:Could you link to the apk? If you can't share, could you at least give the file hash and I'll see if I can find it?
What version of simplify are you using? Your log is showing a lot of errors that very likely could be bugs.

**Comment by maxben14** [comment] 2017-04-12 18:28
Do you get my apk ?12.04.2017, 21:17, "Caleb Fenton" <notifications@github.com>:calebjfenton@gmail.com

**Comment by maxben14** [comment] 2017-04-12 18:30
Do you get my apk on e-mail ?

**Comment by maxben14** [comment] 2017-04-12 18:34
My link on apk http://rgho.st/68gldNwQVLast version simplify uses. I on last day do build simplify. 12.04.2017, 21:13, "Caleb Fenton" <notifications@github.com>:Could you link to the apk? If you can't share, could you at least give the file hash and I'll see if I can find it?What version of simplify are you using? Your log is showing a lot of errors that very likely could be bugs.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by maxben14** [comment] 2017-04-30 00:33
Do you see my apk ?

**Comment by CalebFenton** [comment] 2017-04-30 03:57
Not yet. I've been hella busy with other projects. Maybe tomorrow?

**Comment by maxben14** [comment] 2017-04-30 06:27
Okey, tommorrow)

**Comment by CalebFenton** [comment] 2017-05-28 23:14
This issue should be fixed by https://github.com/CalebFenton/simplify/commit/af3da274ae1109f0cf9f557568f2e4b6fa608652

I ran it with: `-it 'ru/novacard/siticard/ProtectedApp;->engineSign21253' -et 'android/support'`

And got this:
```
Simplifying: Lru/novacard/siticard/ProtectedApp;->engineSign21253()V
Optimizations:
	constantized ifs = 0
	constantized ops = 69
	dead assignments removed = 82
	dead ops removed = 50
	dead results removed = 10
	nops removed = 1
	peephole optmizations = 5
	unreflected fields = 0
	unreflected methods = 0
	useless gotos removed = 0
```

Within `engineSign21253` there were several decrypted strings.

**Closed by CalebFenton** 2017-05-28 23:14 UTC

**Comment by maxben14** [comment] 2017-05-29 10:26
Hi, thank you. Can me on e-mail new apk send please ?)

**Comment by CalebFenton** [comment] 2017-05-29 17:42
Done.

**Comment by maxben14** [comment] 2017-05-29 18:03
Thank you)

**Comment by parind** [comment] 2018-01-23 11:24
I have one similiar problem. Just that it delivers an error linked to other method. Its protected with DexProtector and it also had one smali in Memory which I have dumped as it was nowhere to be found in DEX file. Caleb if you are free can I send you by email. You can check it later.
However I am attaching the output below.

[output.txt](https://github.com/CalebFenton/simplify/files/1655633/output.txt)

**Comment by CalebFenton** [comment] 2018-01-24 01:54
@parind thanks for the report, and for attaching the output since I need that to reproduce. Since this issue is closed, could you open a new issue? Feel free to link to this one.
