### ISSUE TITLE
need a option to specify external jar

### ISSUE THREAD

**Issue by GovindSharma123** [CalebFenton/simplify#118] opened 2018-11-28 04:03 UTC
hi dev thanks for great tool . i am using it by ( java -jar simplify.jar classes.dex) , that apk has xposed method so simplify give error like de/rob/xposed/hook not found . any fix so i can specify a external jar with it

**Comment by CalebFenton** [comment] 2018-11-30 18:12
I haven't investigated the dexlib2 API very much, so I'm not sure how "multi-dex aware" it is. The problem is that, at least how I'm using dexlib, the dexbuilder can only have a single dex file.

I'm also not sure how xposed works. Is it part of the framework / operating system? In any case, dex files are easy to modify. You just find the classes it's expecting and add them to your target dex. If this isn't allowed because it exceeds the method limit, try deleting some ad libraries from the dex.

I'm closing this as it seems to be a duplicate of https://github.com/CalebFenton/simplify/issues/107. Feel free to continue discussion here, though.

**Closed by CalebFenton** 2018-11-30 18:12 UTC
