### ISSUE TITLE
I can not get a result

### ISSUE THREAD

**Issue by ghost** [CalebFenton/simplify#74] opened 2017-05-25 08:24 UTC
WARN  InvokeOp     - Method had possible execution path which throws an exception but cannot instantiate it because the value is unknown. Exception item: type=Lcom/google/android/gms/common/internal/safeparcel/b;, value=*unknown*

ERROR NodeExecutor - ExecutionNode{signature=Lcom/google/android/gms/maps/model/StreetViewPanoramaOrientation;-><init>(IFF)V, op=invoke-static {r0, r1}, Lcom/google/android/gms/common/internal/bn;->b(ZLjava/lang/Object;)V} unhandled virtual exception: {}
java.lang.IllegalArgumentException: Tilt needs to be between -90 and 90 inclusive
04:20:46.978 WARN  InvokeOp     - Unhandled virtual exception: java.lang.IllegalArgumentException: Tilt needs to be between -90 and 90 inclusive

i always get these messages and there is no  output .
i use simplify like this : java -jar simplify/build/libs/simplify.jar classes.dex -o test.dex

Am i doing something wrong?

**Comment by CalebFenton** [comment] 2017-05-25 18:58
Thanks for the error report. I've been hella busy but I appreciate having these ready.

The best way to improve your chances of success are to limit simplify to just a few classes or even methods you care about. It turns out that virtualizing the entire dalvikvm is hard, so there are some bugs. In this case, it looks like you're simplifying some google library shit, which doesn't matter at all and should probably be skipped. Try limiting simplify with `-it just/the/classes/i/care/about` or if you have a single method you care about `com/whatever/SomeFactoryFactory;->createFactoryBecauseJavaLOL\(`

Could you post the hash of the file anyway? This might be surfacing a legit bug.

**Comment by CalebFenton** [comment] 2017-05-28 23:15
Please post at least a file hash so I can reproduce and try to fix. Otherwise, I'll assume it magically fixed itself and close the issue so I can feel better about myself.

**Comment by berfintanriverdi** [comment] 2017-06-04 09:34
Sorry, i couldnt respond long time. 
For my project i must deobfucate all of apk files.

**Comment by CalebFenton** [comment] 2017-06-04 17:31
Your words, when parsed, equate to: "I must either deobfuscate the app entirely or not at all", which sounds highly implausible. I'm going to presume this is not actually true. I understand you want to deobfuscate the entire app, and I also use this for malware, but you're going to need to use simplify more carefully. I recommend you start with classes you think are most interesting and deobfuscate a bit at a time. When you find a method which fails, deobfuscate the methods around it. Simplify might not do the entire app, but it might do 90% of it, which makes doing the other 10% manually a lot easier. 

If you find a bug or something you think is a bug, by all means post an issue and I'll try and fix it.  Unfortunately, it's nearly impossible for me to fix anything without reproducing it, so I'll need the file hash every single time.

**Closed** 2017-07-28 23:39 UTC
