### ISSUE TITLE
Simplify can't deobfuscate dex with longest class name (255 bytes >)

### ISSUE THREAD

**Issue by evildog1** [CalebFenton/simplify#69] opened 2017-04-09 15:04 UTC
I came across an app that have longest class name that is more than 255 bytes. When i try to deobfuscate it with simplify, it got a bunch of errors

And a problem is NTFS file system have 255 bytes characters limit. apktool can decompile them with errors but can't compile it back.

```
Error occurred while disassembling class Luk.co.senab.photoview.a.kI8ueM4bEPkWs5RNkVUYFDvP8nFV4PsmHnkjnXdKdzpuSGXTbdWPHdGLcyIASwyjkAe2fcWLVygyjcaPeXTWhkgZ0AXE4y8YXvKL2OoMKBrTwkwU4kvRIKBoL26I7tL3hU3GOqpkK3XDxjqTqh1ex5HUa30bshMDFgUlqGe3ndzsKyDaBI7v; - skipping class
org.jf.util.ExceptionWithContext: Encountered small uint that is out of range at offset 0x80ae66
        at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:58)
        at org.jf.dexlib2.dexbacked.instruction.DexBackedInstruction31c.getReference(DexBackedInstruction31c.java:55)
        at org.jf.baksmali.Adaptors.Format.InstructionMethodItem.writeTo(InstructionMethodItem.java:104)
        at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:240)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:327)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

org.jf.util.ExceptionWithContext: The last instruction in the method is truncated
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:87)
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:75)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409)
        at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:692)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209)
        at org.jf.baksmali.Adaptors.MethodDefinition.<init>(MethodDefinition.java:92)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:326)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Error while processing method Lorg/c3YLWJcAf0LXAYrL1ZB5Vv4xYb7k1ayMiFzKAD2BplLoqnLwlkus137n2mx2RkDwd8rzBd1MpzIvOYYcKS6dJCe157u1fMUNk3i0uauzca8DoxKyezAmbz7hiDX5Mzly88yZha9VQs2bi1tccRIAhQP5ZT3wKKHvDtot837EXvEbSdnOrYNm;->LWqXnUGjxLchbH7uW5ALB19cnuy3mjAUlCQc3flSkeyiJorCRPw6rPiNVfDwqRhARJ8Qx6TaEDbG6xZEnZ1OgJzpPEi53fvxE0mHbhMy5GbgCy8myUeN9B31cU0VmpiwbJrTMaKzWMyo6gsfB5sY5B1T375ljltwF3lU5eZvpwocomngFGpx()Ljava/lang/String;
```

**Comment by CalebFenton** [comment] 2017-04-09 15:58
I don't think simplify writes any smali files to disk. Dexlib might be doing it behind the scenes but I really don't think it's happening. However, this error `org.jf.util.ExceptionWithContext: Encountered small uint that is out of range at offset 0x80ae66` might be related to long class names. If it's not an invalid dex, you should post a bug report to smali project.

The second error. `The last instruction in the method is truncated` is a error I see a lot with obfuscated samples. Never looked into it. I think some cases are fixed in latest (unreleased) versions of dexlib. Again, this is a problem with the library simplify uses for disassembly and I'm sure they'd be happy to hear about these bugs. (Try disassembling them with _just_ baksmali since apktool uses dexlib also)

**Comment by CalebFenton** [comment] 2017-04-12 18:14
I'm closing this since it really looks like the problem is entirely with dexlib and there's no way for me to work around it other than to fix dexlib or use another library.

**Closed by CalebFenton** 2017-04-12 18:14 UTC
