### ISSUE TITLE
Windows: Illegal character in opaque part

### ISSUE THREAD

**Issue by joswr1ght** [CalebFenton/simplify#67] opened 2017-02-27 21:10 UTC
When using Simplify on Windows, users get an error message `java.lang.IllegalArgumentException: Illegal character in opaque part at index ...`. See attached.

This seems to be a bug in the ZipFileSystem provider on Windows. I've experimented with `zip.getAbsolutePath().replace("\\","/");` and not using paths with spaces, but those changes only produce `URI is not hierarchical` errors.

![screen shot 2017-02-27 at 1 51 05 pm](https://cloud.githubusercontent.com/assets/1318817/23380030/33bcfcbc-fd07-11e6-8a34-a30c30b0ee1b.png)

**Comment by CalebFenton** [comment] 2017-02-28 18:13
Thanks for the bug report. The screen shot isn't loading. What's the file hash and command you're using to run simplify so I can try and reproduce? Probably an easy fix.

**Comment by joswr1ght** [comment] 2017-02-28 18:23
Not sure why Github is being weird about uploading images. Here is a link: https://www.dropbox.com/s/954lzyxkyz0qv2d/Screen%20Shot%202017-02-27%20at%201.51.05%20PM.png?dl=0

It's the same SecureNotePad.apk file referenced in #63, just run from Windows. I think it's complaining about the use of `\` instead of `/`.

**Comment by CalebFenton** [comment] 2017-03-12 16:46
Could you try with https://github.com/CalebFenton/simplify/commit/46beb8ad762a433bf64a880047c15603436e04c8. I don't have access to a Windows machine right now. I can test it myself in a few days.

**Comment by CalebFenton** [comment] 2017-04-12 18:14
I'm closing this because I think it's fixed. Please re-open if I'm wrong.

**Closed by CalebFenton** 2017-04-12 18:14 UTC
