### ISSUE TITLE
Support for Gemalto Obfuscation [for example from MyING.be v8.8.1]

### ISSUE THREAD

**Issue by 5murfette** [CalebFenton/simplify#110] opened 2018-08-18 12:40 UTC
The tool crashes pretty fast with this: http://apktrending.com/apk-android/MyING-be.html
https://play.google.com/store/apps/details?id=MyING.be

**Comment by enovella** [comment] 2018-08-18 13:07
You might want to review this https://github.com/CalebFenton/simplify/issues/98

**Comment by CalebFenton** [comment] 2018-08-18 14:37
Thanks for the report @5murfette. Since there may be multiple bugs, is there any method / class you're interested in particular?

**Comment by enovella** [comment] 2018-08-25 18:40
Hi @5murfette, 

can you open an issue at APKiD Github page to detect this obfuscator?

Cheers

**Comment by CalebFenton** [comment] 2018-10-05 17:49
I'm closing this since there's not enough detail to reproduce. I appreciate the effort to create an issue, but I really need all the details I mention in the readme. This is useful for organizing issues, merging duplicates, prioritizing, etc. In this case, I need to know what code you're trying to deobfuscate, i.e. the specific command you're using.

Feel free to re-open if you feel like sharing.

**Closed by CalebFenton** 2018-10-05 17:49 UTC
